# Generated by Django 3.1.7 on 2021-03-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('api', models.TextField()),
            ],
        ),
    ]
